name: Fly Deploy
on:
  push:
    branches:
      - main    # change to main if needed
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}


# name: Fly.io Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Fly.io CLI
#         uses: superfly/flyctl-actions/setup-flyctl@master

#       - name: Deploy to Fly.io
#         run: |
#           fly deploy --remote-only
#         env:
#           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
